/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function StoveModel(props) {
  const { nodes, materials } = useGLTF("./Stove.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh
          geometry={nodes.Cylinder015.geometry}
          material={materials["Metal Silver"]}
        />
        <mesh
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.Marble062_2K}
        />
        <mesh
          geometry={nodes.Cylinder015_2.geometry}
          material={materials["Metal Black"]}
        />
        <mesh
          geometry={nodes.Cylinder015_3.geometry}
          material={materials.Igniter}
        />
        <mesh
          geometry={nodes.Cylinder015_4.geometry}
          material={materials["Rubber Base"]}
        />
        <mesh
          geometry={nodes.Cylinder015_5.geometry}
          material={materials["Stove Switch"]}
        />
        <mesh
          geometry={nodes.Cylinder015_6.geometry}
          material={materials["Stove Switch Red Mark"]}
        />
        <mesh
          geometry={nodes.Flame_Output.geometry}
          material={materials["Metal Black"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./Stove.glb");
